# Generated by Django 4.1 on 2025-04-25 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extend_id', models.PositiveIntegerField(unique=True)),
                ('username', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('VI', 'Viewed'), ('NV', 'NotViewed')], default='NV', max_length=10)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('telegram_profile_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgm.telegramprofile')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
