# Generated by Django 5.2.4 on 2025-07-29 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_productmarketplaceurl_delete_marketingmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extend_id', models.PositiveIntegerField(unique=True)),
                ('username', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketing/')),
                ('status', models.CharField(choices=[('OK', 'Completed'), ('ER', 'Error'), ('EMPTY', 'Empty')], default='EMPTY', max_length=10)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_marketing', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='CommentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('VI', 'Viewed'), ('NV', 'NotViewed')], default='NV', max_length=10)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_comment', to='product.product')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('telegram_profile_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_comment', to='tgm.telegramprofile')),
            ],
        ),
    ]
