# Generated by Django 4.1 on 2025-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentproduct',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
