# Generated by Django 4.1 on 2025-03-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='extend_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
