# Generated by Django 4.1 on 2025-04-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productmarketplaceurl_delete_marketingmessage_and_more'),
        ('tgm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproduct',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_comment', to='product.product'),
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='telegram_profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_comment', to='tgm.telegramprofile'),
        ),
        migrations.CreateModel(
            name='MarketingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'Completed'), ('ER', 'Error'), ('EMPTY', 'Empty')], default='EMPTY', max_length=10)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketing/')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_marketing', to='product.product')),
            ],
        ),
    ]
