# Generated by Django 4.1 on 2025-04-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgm', '0002_alter_commentproduct_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingmessage',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
