# Generated by Django 4.1 on 2025-04-05 19:10

from django.db import migrations, models
import product.validation


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='name',
            field=models.CharField(max_length=100, validators=[product.validation.MinCharacterValidator(2, meassage='Значение не может быть меньше 2 символов.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(validators=[product.validation.MinCharacterValidator(2, meassage='Значение не может быть меньше 2 символов.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, validators=[product.validation.MinCharacterValidator(2, meassage='Значение не может быть меньше 2 символов.')]),
        ),
        migrations.AlterField(
            model_name='productmarketplace',
            name='url',
            field=models.URLField(),
        ),
    ]
