# Generated by Django 4.1 on 2025-04-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMarketplaceUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='ссылка на маркетплейс')),
                ('marketplace_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_url', to='product.marketplace')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_url', to='product.product')),
            ],
            options={
                'unique_together': {('product_id', 'marketplace_id')},
            },
        ),
        migrations.DeleteModel(
            name='MarketingMessage',
        ),
        migrations.DeleteModel(
            name='ProductMarketplace',
        ),
    ]
