# Generated by Django 4.1 on 2025-04-24 13:03

from django.db import migrations, models
import product.validation


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_marketplace_name_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='name',
            field=models.CharField(max_length=100, validators=[product.validation.MinCharacterValidator(2, meassage='Значение не может быть меньше 2 символов.')], verbose_name='название маркетплейса'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(validators=[product.validation.MinCharacterValidator(2, meassage='Значение не может быть меньше 2 символов.')], verbose_name='описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, validators=[product.validation.MinCharacterValidator(2, meassage='Значение не может быть меньше 2 символов.')], verbose_name='название товара'),
        ),
        migrations.AlterField(
            model_name='productmarketplace',
            name='url',
            field=models.URLField(verbose_name='ссылка на маркетплейс'),
        ),
    ]
